apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: devsupanut/cart-app
        imagePullPolicy: Always
        name: payment
        ports:
        - containerPort: 3000
