apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-sut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080